"""empty message

Revision ID: 2d2e53609964
Revises: e9b176936f86
Create Date: 2019-02-28 23:01:06.930168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d2e53609964'
down_revision = 'e9b176936f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment_type', sa.String(length=32), nullable=True))
    op.add_column('comments', sa.Column('reply_to', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'reply_to')
    op.drop_column('comments', 'comment_type')
    # ### end Alembic commands ###
