"""add cover to article

Revision ID: 34b38a9d96b9
Revises: 9b68bcf823d7
Create Date: 2019-02-23 15:44:36.216170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b38a9d96b9'
down_revision = '9b68bcf823d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('cover', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'cover')
    # ### end Alembic commands ###
