"""add article_type to Article

Revision ID: a5259e81cbdf
Revises: 9cd50e4e75f7
Create Date: 2019-02-05 15:41:30.953402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5259e81cbdf'
down_revision = '9cd50e4e75f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('article_type', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'article', ['article_type'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='unique')
    op.drop_column('article', 'article_type')
    # ### end Alembic commands ###
