"""add Articletype model

Revision ID: d78690727292
Revises: a5259e81cbdf
Create Date: 2019-02-05 16:04:31.504311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd78690727292'
down_revision = 'a5259e81cbdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articletypes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('article', sa.Column('articletype_id', sa.Integer(), nullable=True))
    op.drop_index('article_type', table_name='article')
    op.create_foreign_key(None, 'article', 'articletypes', ['articletype_id'], ['id'])
    op.drop_column('article', 'article_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('article_type', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.create_index('article_type', 'article', ['article_type'], unique=True)
    op.drop_column('article', 'articletype_id')
    op.drop_table('articletypes')
    # ### end Alembic commands ###
