"""empty message

Revision ID: ddfa22c5d731
Revises: d78690727292
Create Date: 2019-02-08 12:32:18.095415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddfa22c5d731'
down_revision = 'd78690727292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('update_timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_article_update_timestamp'), 'article', ['update_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_update_timestamp'), table_name='article')
    op.drop_column('article', 'update_timestamp')
    # ### end Alembic commands ###
