"""add article_source model

Revision ID: fde9aa91768b
Revises: ddfa22c5d731
Create Date: 2019-02-08 17:25:57.259821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde9aa91768b'
down_revision = 'ddfa22c5d731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articlesources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('article', sa.Column('articlesource_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'article', 'articlesources', ['articlesource_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'articlesource_id')
    op.drop_table('articlesources')
    # ### end Alembic commands ###
